FROM node:20-alpine

ARG NEXT_PUBLIC_RAPID_API_KEY
ENV NEXT_PUBLIC_RAPID_API_KEY=$NEXTPUBLICRAPIDAPIKEY

ARG NEXT_PUBLIC_IMAGIN_API_KEY
ENV NEXT_PUBLIC_IMAGIN_API_KEY=$NEXTPUBLICIMAGINAPIKEY

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
ENTRYPOINT ["npm", "run", "start"]